### ISSUE TITLE
Will it work on bottom navigation bar?

### ISSUE THREAD

**Issue by thorep** [Zachariah-Abraham/glass#2]
Would love for this to work on the bottom navbar

**Comment by easonccc** [comment]
I also encountered the same problem. When applying it on the bottom tab bar, the blurring degree of the bottom section is smaller than the above. How to solve this problem?

**Comment by Zachariah-Abraham** [comment]
@thorep @easonccc 
Using BottomNavigationBar.asGlass() seems to work as intended. Note that you may have to set elevation: 0 and backgroundColor: Colors.transparent on BottomNavigationBar (if the elevation is non-zero, you will see a dark shadow under the navbar, and if the color is anything besides transparent, you won't be able to achieve the glass effect.)

Sample code from flutter.dev for BottomNavigationBar, modified to achieve the glass effect: 

```dart
    bottomNavigationBar: BottomNavigationBar(
        elevation: 0,
        backgroundColor: Colors.transparent,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.business),
            label: 'Business',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.school),
            label: 'School',
          ),
        ],
      ).asGlass(frosted: false, tintColor: Colors.blue),
```
Output: 
![image](https://user-images.githubusercontent.com/24973509/181935695-e9111722-13e2-4003-9840-b1ac9b74c013.png)
