### ISSUE TITLE
no blur

### ISSUE THREAD

**Issue by mennovanhout** [Zachariah-Abraham/glass#4]
the blur doesn't work?
its a container with asblur inside a container with boxdecoration image:
![image](https://github.com/Zachariah-Abraham/glass/assets/26040589/d01caff5-d8b0-4c9f-b654-56870ebf1d13)

**Comment by Zachariah-Abraham** [comment]
Hi @mennovanhout 
Are you still facing this issue? If so, could you provide an MRE?

**Comment by mennovanhout** [comment]
> Hi @mennovanhout 
> Are you still facing this issue? If so, could you provide an MRE?

Yes sadly, what is an MRE? 😅

**Comment by Zachariah-Abraham** [comment]
Hi @mennovanhout, an MRE is an Minimal Reproducible Example. A short snippet of code that runs the app and shows the issue.

**Comment by Zachariah-Abraham** [comment]
Closing due to lack of information. Will reopen if there's an MRE.
