### ISSUE TITLE
Suggestion: bool enable/disable

### ISSUE THREAD

**Issue by sidetraxaudio** [Zachariah-Abraham/glass#5]
Great work.
Being able to pass a bool to enable/disable would be very helpful in use in places like button toggles or selections.

**Comment by Zachariah-Abraham** [comment]
> Great work.
> Being able to pass a bool to enable/disable would be very helpful in use in places like button toggles or selections. 

Excellent suggestion. I'll work on this next.

**Comment by Zachariah-Abraham** [comment]
Hi @sidetraxaudio 
I've implemented an `enabled` param to enable or disable all effects (v2.0.0). As a side effect, the `asGlass` method now returns `Widget` instead of `ClipRRect`. Thank you for the suggestion!

**Comment by sidetraxaudio** [comment]
Excellent work.  Thanks for that.
It's now super easy to use external controls to change the filter reactively and it works very well
Cheers.
